### PR TITLE
Bugfix/event change date

### LINKED ISSUE #800: [BUG] There is no time validation on the schedule tab when you update the lecture event by changing the date
**Preconditions:**
Registered headman profile; 
The Lecture event has been created in the schedule.

**Steps to reproduce**
1. Open FICT Advisor.
2. Go to the schedule tab.
3. Click on the already created event Lecture.
4. Click on Edit button.
5. Change the event date
6. Pay attention to the updated event.

**Actual result:**

https://github.com/fictadvisor/fictadvisor-web/assets/128691252/e676c873-ef55-4ae5-805e-96f99b58318b

**Expected result:**

Image

-deploy: prod, dev
-url: https://dev.fictadvisor.com/schedule?group=b49dd1d3-5111-4c74-a10c-768f958a19da
-OS: Windows 11 Pro
-browser: Google Chrome

### PR DESCRIPTION
**Pull request by sifes**
closed #800

### CODE REVIEW

**Review by IlliaSatyrenko — COMMENTED** [review]
the time on the edit popup is not equal to the event time

**Review by IlliaSatyrenko — APPROVED** [review]
Approve)

**Comment by papiroskada** [comment]
qa approved

File: src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/components/schedule-dropdown/TimeScheduleDropdown.tsx [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+export const TimeScheduleDropdown: FC<TimeScheduleDropdownProps> = ({
+  clearOnUnmount,
+  name,
+  date,
+  ...props
+}) => {
+  const [{ value }, { touched, error }, { setValue, setTouched }] =
+    useField(name);
+
+  React.useEffect(() => {
```
Comment (Markusplay) [inline src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/components/schedule-dropdown/TimeScheduleDropdown.tsx:25]: remove explicit `React` call

File: src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/components/schedule-dropdown/TimeScheduleDropdown.tsx [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+    setValue(getDateWithTimeSetted(date, value));
+  }, [date, value, setValue]);
```
Comment (Markusplay) [inline src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/components/schedule-dropdown/TimeScheduleDropdown.tsx:27]: why do we need `setValue` on dependency?

File: src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/components/schedule-dropdown/TimeScheduleDropdown.tsx [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+
+  return (
+    <Dropdown
+      {...props}
+      value={value}
+      touched={touched}
+      error={error}
+      showRemark={!!error}
+      dropdownSx={styles.dropdown}
+      inputSx={styles.input()}
```
Comment (Markusplay) [inline src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/components/schedule-dropdown/TimeScheduleDropdown.tsx:42]: why input is called as function?

File: src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/components/schedule-dropdown/TimeScheduleDropdown.tsx [hunk 4]
```diff
@@ -0,0 +1,48 @@
...
+      onChange={onChange}
+      label={''}
```
Comment (Markusplay) [inline src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/components/schedule-dropdown/TimeScheduleDropdown.tsx:44]:
```suggestion
      label=""
```

File: src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/components/schedule-dropdown/TimeScheduleDropdown.tsx [hunk 5]
```diff
@@ -0,0 +1,48 @@
...
+
+import { getDateWithTimeSetted } from '../../utils/getDateWithTimeSetted';
+
+import * as styles from './ScheduleDropdown.styles';
+
+interface TimeScheduleDropdownProps extends FormikDropdownProps {
+  date: dayjs.Dayjs;
+}
+
+export const TimeScheduleDropdown: FC<TimeScheduleDropdownProps> = ({
```
Comment (Markusplay) [inline src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/components/schedule-dropdown/TimeScheduleDropdown.tsx:16]: we don't export components in such way. Should be:
`const TimeScheduleDropdown...`
`export default TimeScheduleDropdown`

File: src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/utils/getDateWithTimeSetted.ts
Comment (Markusplay) [inline src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/utils/getDateWithTimeSetted.ts:1]: Wrong English.
image

**Review by Markusplay — CHANGES_REQUESTED** [review]

File: src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/components/schedule-dropdown/TimeScheduleDropdown.tsx (hunk 2 above)
Comment (sifes) [reply src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/components/schedule-dropdown/TimeScheduleDropdown.tsx:27]: image_2023-11-23_161747838

File: src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/components/schedule-dropdown/TimeScheduleDropdown.tsx (hunk 3 above)
Comment (sifes) [reply src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/components/schedule-dropdown/TimeScheduleDropdown.tsx:42]: because it is a function, i guess, and why is that i actually don`t know, because it isn`t written by me
image

**Review by Markusplay — APPROVED** [review]
